dist: xenial
sudo: required
language: generic

notifications:
  slack: uwsailbot:5Q2oPJ7OdRTvkEu8R7OH8fCV

env:
  matrix:
    - ROS_DISTRO="kinetic" ROS_REPOSITORY_PATH=http://packages.ros.org/ros/ubuntu
    - ROS_DISTRO="kinetic" ROS_REPOSITORY_PATH=http://packages.ros.org/ros-shadow-fixed/ubuntu

matrix:
  allow_failures:
    - env: ROS_DISTRO="kinetic" ROS_REPOSITORY_PATH=http://packages.ros.org/ros-shadow-fixed/ubuntu

################################################################################

install:
  - ./dependencies.sh
  - git clone https://github.com/ros-industrial/industrial_ci.git .ci_config
script:
  - yapf --diff --recursive .
  - .ci_config/travis.sh
