
# Use ubuntu trusty (14.04) with sudo privileges. Xenial is not yet supported
dist: trusty
sudo: required
language: generic
cache:
    directories:
- "~/.platformio"
env:
  global:
    - CI_SOURCE_PATH=$(pwd)
    - PLATFORMIO_CI_SRC=boat_interfaces/arduino/PS4_Controller/PS4_Controller.ino
    - PLATFORMIO_CI_SRC=boat_interfaces/arduino/boat_control/boat_control.ino
    - PLATFORMIO_CI_SRC=boat_interfaces/arduino/boat_control/anemometer_lookup_table.ino
    - PLATFORMIO_CI_SRC=boat_interfaces/arduino/boat_control/anemometer_filter.ino     
    - DEPEND_FILE=$CI_SOURCE_PATH/dependencies.sh
    - POST_FILE =$CI_SOURCE_PATH/post.sh
    - BEFORE_SCRIPT='if [[ -f $DEPEND_FILE ]] ; then . $DEPEND_FILE ; fi'
    - AFTER_SCRIPT='if [[ -f $POST_FILE ]] ; then . $POST_FILE ; fi'
    # Set the python path manually to include /usr/-/python2.7/dist-packages
    # as this is where apt-get installs python packages.
    - PYTHONPATH=$PYTHONPATH:/usr/lib/python2.7/dist-packages:/usr/local/lib/python2.7/dist-packages
    - USE_DEB=true  ROS_DISTRO="kinetic"   ROS_REPOSITORY_PATH=http://packages.ros.org/ros/ubuntu
    - USE_DEB=true  ROS_DISTRO="kinetic"   ROS_REPOSITORY_PATH=http://packages.ros.org/ros-shadow-fixed/ubuntu
matrix:
  allow_failures:
    - env: USE_DEB=true  ROS_DISTRO="kinetic"   ROS_REPOSITORY_PATH=http://packages.ros.org/ros-shadow-fixed/ubuntu
notifications:
  slack: uwsailbot:5Q2oPJ7OdRTvkEu8R7OH8fCV

################################################################################

install:
  - git clone https://github.com/ros-industrial/industrial_ci.git .ci_config
script:
  - .ci_config/travis.sh
